const { ethers } = require('ethers');
require('dotenv').config();

const PRIVATE_KEY = process.env.PRIVATE_KEY;

console.log('🔐 Wallet Information:');
console.log('='.repeat(50));

// Create wallet from private key
const wallet = new ethers.Wallet(PRIVATE_KEY);

console.log(`📍 Wallet Address: ${wallet.address}`);
console.log(`🔑 Private Key: ${PRIVATE_KEY.substring(0, 6)}...${PRIVATE_KEY.substring(PRIVATE_KEY.length - 4)}`);
console.log(`📝 Public Key: ${wallet.publicKey}`);

console.log('\n💡 How to import into MetaMask:');
console.log('='.repeat(50));
console.log('1. Open MetaMask');
console.log('2. Click "Import Account" (NOT "Create new wallet")');
console.log('3. Select "Private Key" tab');
console.log('4. Paste your private key (from .env file)');
console.log('5. Click "Import"');

console.log('\n⚠️  IMPORTANT:');
console.log('- You don\'t have a seed phrase for this wallet');
console.log('- This private key was generated by your trading bot');
console.log('- Keep this private key safe - it\'s your only way to access this wallet');
console.log('- NEVER share your private key with anyone');

console.log('\n🌐 After importing to MetaMask:');
console.log('1. Switch to Polygon network');
console.log('2. Your address should show:', wallet.address);
console.log('3. You should see your USDC balance');
console.log('4. Get some MATIC for gas fees');

// Add a check to help with USDC token visibility
console.log('\n💰 To see USDC in MetaMask:');
console.log('1. Click "Import tokens" in MetaMask');
console.log('2. Enter USDC contract address: 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174');
console.log('3. Token Symbol: USDC');
console.log('4. Decimals: 6');
